GI-plan
ks-no/fiks-protokoll-validator pull request #251
Opened 2021-07-16 13:42 UTC by OlaStalberg

Initial GI-plan commit. 

- Added GI-plan to protokoll-validator. Front- and backend
- Added updatebutton fix. Ref Issue # 204
- Added tests for GI-plan
- Small fix to TestSeeder-AddFiksExpectedResponseMessageTypes.

2021-07-26 09:14 UTC, jarleborsheim requested changes
Det er litt nitpicking her (markert med [NIT]) som det er fint hvis du ser over. 
Ellers ser det ok ut.

2021-07-26 09:14 UTC, jarleborsheim commented on api/KS.FiksProtokollValidator.WebAPI/FiksIO/FiksResponseMessageService.cs
> +
Trenger vi en newline her? ;) 
Synes det er lurt å ikke touche en fil unødvendig.

2021-07-26 09:14 UTC, jarleborsheim commented on web-ui/src/components/TestSession.vue
> +          }else {
Ville tatt denne på en ny linje slik at det følger resten av kodestilen?

2021-07-26 09:14 UTC, jarleborsheim commented on web-ui/src/components/NewTestSession.vue
> +
[NIT] Jeg er visst i det kranglete hjørnet i dag. Unødvendig med tom linje. ;)

2021-07-26 09:14 UTC, jarleborsheim commented on api/KS.FiksProtokollValidator.WebAPI/TestCases/no.ks.fiks.gi.plan.klient/OpprettArealplanN1/sampleOpprettArealplan.json
> +
[NIT] Unødvendig med tomme linjer?

2021-08-11 06:35 UTC, jarleborsheim approved these changes
LGTM

2021-09-01 07:27 UTC, jarleborsheim commented
@OlaStalberg På tide å gjøre ferdig denne PR'en? :) Det er bedre å ha flere mindre PR'er enn en stor med mange endringer. Denne var jo godkjent ;) Vil at vi tar en ny review når du er klar.

2021-09-01 09:00 UTC, jarleborsheim requested changes
Se kommentar

2021-09-01 09:11 UTC, OlaStalberg commented on api/KS.FiksProtokollValidator.WebAPI/KS - Backup.FiksProtokollValidator.WebAPI.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk.Web">
Slettet. Usikker på opphavet til denne.

2021-09-01 10:26 UTC, jarleborsheim approved these changes
LGTM 👍

2021-09-07 07:35 UTC, merged